[package]
name = "spool-templates"
version = "0.22.2-local.202602041928"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
include_dir = { workspace = true }
minijinja = { workspace = true }
serde = { workspace = true }
