[package]
name = "spool-templates"
version = "0.21.0-local.202602031650"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
include_dir = { workspace = true }
minijinja = { workspace = true }
serde = { workspace = true }
