[package]
name = "spool-templates"
version = "0.22.3-local.202602050906"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
include_dir = { workspace = true }
minijinja = { workspace = true }
serde = { workspace = true }
